language: android

script: "./gradlew build"
android: 
    components:
        - tools
        - build-tools-23.0.2
        - android-23
        - extra

deploy:
    provider: debug

file: app/build/outputs/apk/app-debug.apk
